# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    twig:
        mode: lazy
<<<<<<< HEAD

    filter_sets:
        mini:
            quality: 75
            filters:
                thumbnail:
                    size: [150, 100]
                    mode: outbound

        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [360, 230]
                    mode: outbound
        avatar:
            quality: 75
            filters:
                thumbnail:
                    size: [150, 150]
                    mode: outbound

        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [800, 530]
                    mode: outbound
=======
>>>>>>> origin/master
