twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@KMSFroalaEditor/Form/froala_widget.html.twig'

when@test:
    twig:
        strict_variables: true
